name: IMage from GPX generator
run-name: ${{ github.actor }} started map image generation 🚀
on: [push]
jobs:
  Generate-images-from-GPX-files:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Generate images
        uses: the-cyclist-diary/generate-map-cicd@v1.2.1
        with:
          content-path: "content"
          user-token: ${{ secrets.GITHUB_TOKEN }}
